config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :movements
  root to: 'users/sessions#new'

  resources :personal_records do
    collection do
      resources(
        :movements,
        only: :index,
        module: :personal_records
      )
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/movement.rb
# frozen_string_literal: true

class Movement < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/movements_controller.rb
# frozen_string_literal: true

class MovementsController < ApplicationController
  before_action :current_movement, only: %i[show edit update destroy]
  before_action :authenticate_admin!

  def index
    @movements = Movement.all
  end

  def show
  end

  def new
    @movement = Movement.new
  end

  def create
    @movement = Movement.new(movement_params)

    if @movement.save
      redirect_to @movement
    else
      render :new
    end
  end

  def edit
  end

  def update
    @movement.update(movement_params)

    redirect_to @movement
  end

  def destroy
    @movement.destroy

    redirect_to movements_path
  end

  private

  def movement_params
    params.require(:movement).permit(:name)
  end

  def current_movement
    @movement = Movement.find(params[:id])
  end
end

app/controllers/personal_records/movements_controller.rb
# frozen_string_literal: true

module PersonalRecords
  class MovementsController < ApplicationController
    before_action :authenticate_user!

    def index
      @movements = Movement.all
    end
  end
end

app/views/movements/_form.html.erb
<div class="form-container">
  <%= form_for @movement do |f|  %>
  <%= form_error_tag (@movement) %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= error_tag(@movement, :name) %>
    </div>

    <div class="form-group">
      <%= f.submit class: 'btn btn-info btn-block' %>
    </div>
  <% end %>
</div>

app/views/movements/edit.html.erb
  <h3 class="page-header"> <%= t '.title' %></h3>
  <%= render 'form', room: @movement %>

app/views/movements/index.html.erb
  <h3 class="list-header"><%= t '.title' %> </h3>
    <div class="list-body">
    <% @movements.each do |movement| %>
      <div class="list-item">
        <div class="col-md-8 list-item__name"><%= link_to movement.name, movement_path(movement) %></div>
        </div>
    <% end %>
  </div>
  <%= button_to t('.new'), new_movement_path, method: :get, class: 'btn btn-info'%>

app/views/movements/new.html.erb
<h3 class="page-header">New Movement</h3>
<%= render 'form', movement: @movement %>

app/views/movements/show.html.erb
<%= @movement.name %>

<%= button_to t('.back'), movements_path, method: :get %>
<%= button_to t('.edit'), edit_movement_path(@movement), method: :get %>
<%= button_to t('.destroy'), movement_path(@movement), method: :delete, data: { confirm: t(:confirm_message) } %>