config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :movements
  root to: 'users/sessions#new'

  resources :personal_records do
    collection do
      resources(
        :movements,
        only: :index,
        module: :personal_records
      )
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/personal_record.rb
# frozen_string_literal: true

class PersonalRecord < ApplicationRecord
  validates_uniqueness_of :date, scope: %i[user_id movement_id]
  belongs_to :movement
  belongs_to :user

  scope :newest, lambda {
    where(%(
      personal_records.date = (
        SELECT MAX(date) FROM personal_records pr
        WHERE pr.movement_id = personal_records.movement_id
      )
    ))
  }
end

app/controllers/personal_records/movements_controller.rb
# frozen_string_literal: true

module PersonalRecords
  class MovementsController < ApplicationController
    before_action :authenticate_user!

    def index
      @movements = Movement.all
    end
  end
end

app/controllers/personal_records_controller.rb
# frozen_string_literal: true

class PersonalRecordsController < ApplicationController
  before_action :current_personal_record, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @personal_records =
      current_user.personal_records.newest
                  .includes(:movement)
                  .order('movements.name')
  end

  def show
    @personal_records = current_user.personal_records.where(
      movement: @personal_record.movement
    ).order(date: :desc)
  end

  def new
    @personal_record = current_user.personal_records.build
    @personal_record.movement_id = personal_record_params[:movement_id]
  end

  def create
    @personal_record = current_user.personal_records
                                   .build(personal_record_params)

    if @personal_record.save
      redirect_to @personal_record
    else
      render :new
    end
  end

  def destroy
    @personal_record.destroy

    redirect_to personal_records_path
  end

  private

  def personal_record_params
    params.require(:personal_record).permit(:movement_id, :date, :weight)
  end

  def current_personal_record
    @personal_record = current_user.personal_records.find(params[:id])
  end
end

app/helpers/personal_records_helper.rb
# frozen_string_literal: true

module PersonalRecordsHelper
end

app/views/personal_records/_form.html.erb
<div class="form-container">
<%= form_for @personal_record do |f|  %>
<%= form_error_tag (@personal_record) %>
  <%= f.text_field :movement_id, value: @personal_record.movement_id, hidden: true %>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: 'form-control'%>
    <%= error_tag(@personal_record, :date) %>
  </div>
   <div class="form-group">
    <%= f.label :weight %>
    <%= f.number_field :weight, class: 'form-control' %>
    <%= error_tag(@personal_record, :weight) %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-info btn-block' %>
  </div>
<% end %>
</div>

app/views/personal_records/index.html.erb
    <h3 class="list-header"><%= t '.title' %> </h3>
    <div class="list-body">
    <% @personal_records.each do |personal_record| %>
      <div class="list-item">
        <div class="col-md-8 list-item__name"><%= link_to personal_record.movement.name, personal_record_path(personal_record) %></div>
        <div className="list-item__weight"><%= link_to personal_record.weight, personal_record_path(personal_record) %> </div>
      </div>
    <% end %>
    </div>
  <%= button_to t('.new'), '/personal_records/movements', method: :get, class: 'btn btn-info' %>

app/views/personal_records/new.html.erb
<h3 class="page-header"><%= @personal_record.movement.name %></h3>
<%= render 'form', personal_record: @personal_record %>

app/views/personal_records/show.html.erb
<div class="content-container">
  <h3 class="list-header"><%= t '.title' %> </h3>
  <div class="list-body">
  <% @personal_records.each do |personal_record| %>
    <div class="list-item">
      <%= personal_record.date %> - <%= personal_record.weight %>
      <%= button_to t('.destroy'), personal_record_path(personal_record), method: :delete, data: { confirm: t(:confirm_message) }, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

<%= link_to t('.new'), new_personal_record_path(personal_record: { movement_id: @personal_record.movement_id }), class: 'btn btn-info' %>
<%= link_to t('.back'), personal_records_path, method: :get, class: 'btn btn-default' %>