config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :movements
  root to: 'users/sessions#new'

  resources :personal_records do
    collection do
      resources(
        :movements,
        only: :index,
        module: :personal_records
      )
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_navbar.html.erb
<nav>
  <% if admin_signed_in? %>
    <%= current_admin.email %>
    <%= link_to 'sair', destroy_admin_session_path, method: :delete %>
  <% end %>
</nav>

app/views/layouts/_user_navbar.html.erb
<nav>
  <% if user_signed_in? %>
    <%= current_user.email %>
    <%= link_to 'sair', destroy_user_session_path, method: :delete %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trackbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/user_navbar' %>
    <% end %>

    <% if admin_signed_in? %>
      <%= render 'layouts/admin_navbar' %>
    <% end %>

    <div class="content-container">
      <%= yield %>
    <div>
  </body>
</html>